// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoMeSimulator.Data;

namespace SoMeSimulator.Migrations
{
    [DbContext(typeof(SoMeContext))]
    [Migration("20200513143313_UsrSessionGroup")]
    partial class UsrSessionGroup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SoMeSimulator.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<uint>("MessageFlow");

                    b.Property<uint>("Props");

                    b.Property<int?>("ScenarioId");

                    b.Property<string>("Sender");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("ScenarioId");

                    b.Property<double>("StartPercent");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.PhaseComment", b =>
                {
                    b.Property<int>("PhaseId");

                    b.Property<int>("CommentId");

                    b.HasKey("PhaseId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("PhaseComments");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.PhasePost", b =>
                {
                    b.Property<int>("PhaseId");

                    b.Property<int>("PostId");

                    b.HasKey("PhaseId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("PhasePosts");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<string>("Heading");

                    b.Property<uint>("MessageFlow");

                    b.Property<string>("Sender");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.ScenarioEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Heading");

                    b.Property<int>("PhaseId");

                    b.Property<string>("Sender");

                    b.Property<string>("Text");

                    b.Property<double>("TimePercent");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("ScenarioEvents");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Participant");

                    b.Property<int?>("ScenarioId");

                    b.Property<int?>("SessionGroupId");

                    b.Property<Guid>("SessionGuid");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("SessionGroupId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.SessionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CurrentPhaseId");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("GroupName");

                    b.Property<DateTime?>("PauseStart");

                    b.Property<TimeSpan>("PauseTimeSum");

                    b.Property<int>("ScenarioId");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("StopDate");

                    b.Property<uint>("StressLevel");

                    b.Property<string>("TypeableCode");

                    b.Property<int?>("UsrId");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPhaseId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("UsrId")
                        .IsUnique();

                    b.ToTable("SessionGroups");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.SessionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar");

                    b.Property<uint>("BotReplyProperties");

                    b.Property<int?>("CommentId");

                    b.Property<string>("Heading");

                    b.Property<int>("Level");

                    b.Property<uint>("MessageFlow");

                    b.Property<int?>("ParentSessionLogId");

                    b.Property<int?>("PostId");

                    b.Property<int?>("ScenarioEventId");

                    b.Property<DateTime?>("SendDateTime");

                    b.Property<string>("Sender");

                    b.Property<int?>("SessionId");

                    b.Property<uint>("Tag");

                    b.Property<string>("Text");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ParentSessionLogId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionLogs");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RoleId");

                    b.Property<int>("UsrId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UsrId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.Usr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.Comment", b =>
                {
                    b.HasOne("SoMeSimulator.Data.Models.Scenario", "Scenario")
                        .WithMany("Comments")
                        .HasForeignKey("ScenarioId");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.Phase", b =>
                {
                    b.HasOne("SoMeSimulator.Data.Models.Scenario", "Scenario")
                        .WithMany("Phases")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.PhaseComment", b =>
                {
                    b.HasOne("SoMeSimulator.Data.Models.Comment", "Comment")
                        .WithMany("PhaseLink")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoMeSimulator.Data.Models.Phase", "Phase")
                        .WithMany("CommentLink")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.PhasePost", b =>
                {
                    b.HasOne("SoMeSimulator.Data.Models.Phase", "Phase")
                        .WithMany("PostLink")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoMeSimulator.Data.Models.Post", "Post")
                        .WithMany("PhaseLink")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.ScenarioEvent", b =>
                {
                    b.HasOne("SoMeSimulator.Data.Models.Phase", "Phase")
                        .WithMany("ScenarioEvents")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.Session", b =>
                {
                    b.HasOne("SoMeSimulator.Data.Models.Scenario")
                        .WithMany("Sessions")
                        .HasForeignKey("ScenarioId");

                    b.HasOne("SoMeSimulator.Data.Models.SessionGroup", "SessionGroup")
                        .WithMany("Sessions")
                        .HasForeignKey("SessionGroupId");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.SessionGroup", b =>
                {
                    b.HasOne("SoMeSimulator.Data.Models.Phase", "CurrentPhase")
                        .WithMany()
                        .HasForeignKey("CurrentPhaseId");

                    b.HasOne("SoMeSimulator.Data.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoMeSimulator.Data.Models.Usr", "Usr")
                        .WithOne("ActiveSessionGroup")
                        .HasForeignKey("SoMeSimulator.Data.Models.SessionGroup", "UsrId");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.SessionLog", b =>
                {
                    b.HasOne("SoMeSimulator.Data.Models.SessionLog", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentSessionLogId");

                    b.HasOne("SoMeSimulator.Data.Models.Session", "Session")
                        .WithMany("SessionLogs")
                        .HasForeignKey("SessionId");
                });

            modelBuilder.Entity("SoMeSimulator.Data.Models.UserRole", b =>
                {
                    b.HasOne("SoMeSimulator.Data.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoMeSimulator.Data.Models.Usr", "Usr")
                        .WithMany("UserRoles")
                        .HasForeignKey("UsrId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
